### ISSUE TITLE
Uvloop support

### ISSUE THREAD

**Issue by Kludex** [klen/asgi-prometheus#1]
Sorry to bother you again... :sweat_smile: 

I saw that `uvloop` is not on the `README`, but does it work with it? I guess it does?

**Comment by Kludex** [comment]
It works with `uvloop`.

Running FastAPI with uvicorn (on uvloop) below:
```python
from asgi_prometheus import PrometheusMiddleware
from fastapi import FastAPI

app = FastAPI()
app.add_middleware(PrometheusMiddleware.setup(group_paths=["/"]))


@app.get("/")
def home():
    return "hello"
```

**Comment by klen** [comment]
Yes, I don't see any reason why it shouldn't. Thank you for the testing! 👍
